import { readFile } from "node:fs/promises";
import { writeTextFile, type Logger } from "aem-to-sanity-core";
import type { Report } from "./report.ts";

const GENERATED_MARKER = "__generated";

export interface RegistryField {
  name: string;
  type: string;
  /** Nested item fields when `type === "array-of-object"`. */
  itemFields?: RegistryField[];
}

export interface RegistryEntry {
  resourceType: string;
  sanityType: string;
  /**
   * Tree of every field the emitted Sanity schema declares, with its
   * Sanity `type`. Nested array-of-object members are carried under
   * `itemFields` so `aem-transform` can coerce AEM values at any depth —
   * richtext HTML strings inside multifield items become Portable Text
   * rather than landing as raw strings that the Studio rejects with
   * "expected array".
   */
  fields: RegistryField[];
}

export interface WriteContentRegistryOptions {
  /** Where to write the registry JSON. Usually `./content-type-registry.json`. */
  outputFile: string;
  /** The migration report — source of truth for successful mappings. */
  report: Report;
  /**
   * Strip this JCR prefix from component paths to derive the AEM
   * `sling:resourceType`. Default: `/apps/`.
   */
  jcrPrefix?: string;
  logger?: Logger;
}

export interface WriteContentRegistryResult {
  file: string;
  /** False if we preserved a hand-edited file (no GENERATED marker). */
  written: boolean;
  /** Entry count in the generated file. */
  entryCount: number;
}

/**
 * Emit `content-type-registry.json` from the schema migration's successful
 * mappings. The AEM `sling:resourceType` is derived by stripping `jcrPrefix`
 * from each component path (AEM convention: `/apps/foo/bar` →
 * `foo/bar`). `fields` comes from the mapped Sanity schema.
 *
 * The file wraps its entries under a `__generated` marker so a subsequent
 * run can detect whether the user has taken ownership. If the file exists
 * without the marker, we preserve it and log — so custom overrides for
 * `sling:resourceSuperType` chains don't get stomped.
 */
export async function writeContentRegistry(
  opts: WriteContentRegistryOptions,
): Promise<WriteContentRegistryResult> {
  const { outputFile, report, jcrPrefix = "/apps/", logger } = opts;

  let existing: string | undefined;
  try {
    existing = await readFile(outputFile, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  if (existing !== undefined && !existing.includes(GENERATED_MARKER)) {
    logger?.info(
      `content-registry: preserving hand-authored ${outputFile} (no ${GENERATED_MARKER} marker found)`,
    );
    return { file: outputFile, written: false, entryCount: 0 };
  }

  const entries: RegistryEntry[] = report.results
    .filter((r): r is Extract<typeof r, { status: "success" }> => r.status === "success")
    .map((r) => ({
      resourceType: r.path.startsWith(jcrPrefix)
        ? r.path.slice(jcrPrefix.length)
        : r.path.replace(/^\/+/, ""),
      sanityType: r.sanityTypeName,
      fields: normalizeFieldTree(r.fields),
    }))
    .sort((a, b) => a.resourceType.localeCompare(b.resourceType));

  const payload = {
    __generated:
      "GENERATED by aem-to-sanity-schema. Remove this field (or delete the file) to take ownership; the next run will preserve your edits.",
    entries,
  };

  await writeTextFile(outputFile, JSON.stringify(payload, null, 2) + "\n");
  return { file: outputFile, written: true, entryCount: entries.length };
}

/**
 * Dedup + sort a field tree for stable on-disk output. Fields at each
 * nesting level are deduped by name (keeping the first occurrence, which
 * matches the declaration order in the emitted schema) and sorted
 * alphabetically so re-runs produce byte-identical registries — the
 * deterministic-diff invariant the rest of the pipeline relies on.
 */
function normalizeFieldTree(
  fields: readonly { name: string; type: string; itemFields?: readonly { name: string; type: string; itemFields?: unknown }[] }[],
): RegistryField[] {
  const seen = new Map<string, RegistryField>();
  for (const f of fields) {
    if (seen.has(f.name)) continue;
    const entry: RegistryField = { name: f.name, type: f.type };
    if (f.itemFields?.length) {
      entry.itemFields = normalizeFieldTree(
        f.itemFields as readonly { name: string; type: string }[],
      );
    }
    seen.set(f.name, entry);
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}
