import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { writeTextFile, type Logger } from "aem-to-sanity-core";
import { toTitleCase } from "./naming.ts";

const GENERATED_MARKER = "GENERATED by aem-to-sanity-schema pagebuilder";

export interface PageBuilderMember {
  /** Sanity type name, matches the emitted `defineType.name`. */
  name: string;
  /** Friendly label rendered in Page Builder rows and the "+ Add" menu. */
  title: string;
}

export interface WritePageBuilderArtifactsOptions {
  /** Directory where schema .ts files (including page.ts / pageBuilder.ts) are written. */
  schemasDir: string;
  /**
   * Block-type names to include in `pageBuilder.of[]`. Each entry becomes a
   * `defineArrayMember({ type, title })` so the Page Builder always renders
   * the component's friendly title on array rows — even when a row's data is
   * empty. When a caller knows the friendly titles (the main migration
   * pipeline does), pass {@link componentMembers} instead to avoid the
   * `toTitleCase` fallback.
   */
  componentTypeNames?: string[];
  /** Pre-resolved `{name, title}` pairs. Takes precedence over `componentTypeNames`. */
  componentMembers?: PageBuilderMember[];
  /** Names to exclude from `pageBuilder.of[]` (e.g. page-level components that shouldn't nest inside a page). */
  exclude?: string[];
  /** Name of the generated page document type. Default: "page". */
  pageTypeName?: string;
  /** Name of the generated page-builder array type. Default: "pageBuilder". */
  pageBuilderTypeName?: string;
  logger?: Logger;
}

export interface WritePageBuilderArtifactsResult {
  pageFile: string;
  pageBuilderFile: string;
  /** False if a hand-authored `page.ts` was found and preserved. */
  pageWritten: boolean;
  /** Type names registered in `pageBuilder.of[]`. */
  registered: string[];
}

export async function writePageBuilderArtifacts(
  opts: WritePageBuilderArtifactsOptions,
): Promise<WritePageBuilderArtifactsResult> {
  const {
    schemasDir,
    componentTypeNames,
    componentMembers,
    exclude = [],
    pageTypeName = "page",
    pageBuilderTypeName = "pageBuilder",
    logger,
  } = opts;

  const excludeSet = new Set([...exclude, pageTypeName, pageBuilderTypeName]);

  // Prefer pre-resolved members (names + friendly titles). Fall back to
  // title-casing the type name when only names are provided — the CLI entry
  // point works off on-disk filenames and has no other way to know titles.
  const sourceMembers: PageBuilderMember[] =
    componentMembers && componentMembers.length > 0
      ? componentMembers
      : (componentTypeNames ?? []).map((name) => ({
          name,
          title: toTitleCase(name),
        }));

  const seen = new Set<string>();
  const registeredMembers = sourceMembers
    .filter((m) => {
      if (excludeSet.has(m.name) || seen.has(m.name)) return false;
      seen.add(m.name);
      return true;
    })
    .sort((a, b) => a.name.localeCompare(b.name));
  const registered = registeredMembers.map((m) => m.name);

  const pageBuilderFile = join(schemasDir, `${pageBuilderTypeName}.ts`);
  const pageFile = join(schemasDir, `${pageTypeName}.ts`);

  await writeTextFile(
    pageBuilderFile,
    renderPageBuilder(pageBuilderTypeName, registeredMembers),
  );

  const pageWritten = await maybeWritePage(pageFile, pageTypeName, pageBuilderTypeName, logger);

  return { pageFile, pageBuilderFile, pageWritten, registered };
}

function renderPageBuilder(
  typeName: string,
  members: PageBuilderMember[],
): string {
  const rendered = members
    .map(
      (m) =>
        `    defineArrayMember({ type: ${JSON.stringify(m.name)}, title: ${JSON.stringify(m.title)} }),`,
    )
    .join("\n");
  return `// ${GENERATED_MARKER}. Do not edit by hand.
// Regenerated on every migration run; add or remove members by running:
//   pnpm aem-to-sanity-pagebuilder --output-dir <dir>
import { defineArrayMember, defineType } from "sanity";

export const ${typeName} = defineType({
  name: ${JSON.stringify(typeName)},
  type: "array",
  of: [
${rendered}
  ],
});
`;
}

function renderPage(pageTypeName: string, pageBuilderTypeName: string): string {
  return `// ${GENERATED_MARKER}. Safe to delete or replace.
// To author a custom page schema, remove this file (or the marker comment) — the
// migration will not overwrite it. Custom page types can still reference the
// generated ${pageBuilderTypeName} array.
import { defineField, defineType } from "sanity";

export const ${pageTypeName} = defineType({
  name: ${JSON.stringify(pageTypeName)},
  title: "Page",
  type: "document",
  preview: {
    select: {
      title: "title",
      slug: "slug.current",
    },
    prepare({ title, slug }) {
      return {
        title: typeof title === "string" && title.trim() ? title.trim() : "Untitled page",
        subtitle:
          typeof slug === "string" && slug.trim() ? "/" + slug.trim() : undefined,
      };
    },
  },
  fields: [
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: ${JSON.stringify(pageBuilderTypeName)}, type: ${JSON.stringify(pageBuilderTypeName)} }),
  ],
});
`;
}

async function maybeWritePage(
  pageFile: string,
  pageTypeName: string,
  pageBuilderTypeName: string,
  logger: Logger | undefined,
): Promise<boolean> {
  let existing: string | undefined;
  try {
    existing = await readFile(pageFile, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  if (existing !== undefined && !existing.includes(GENERATED_MARKER)) {
    logger?.info(
      `pagebuilder: preserving hand-authored ${pageFile} (no GENERATED marker found)`,
    );
    return false;
  }

  await writeTextFile(pageFile, renderPage(pageTypeName, pageBuilderTypeName));
  return true;
}

/**
 * Scan a schemas directory for emitted type files. Returns the list of
 * exported type names, inferred from filenames (one type per file, matching
 * the emitter convention). `index.ts`, the page type, and the page-builder
 * type are excluded from the result.
 */
export async function scanSchemaTypeNames(
  schemasDir: string,
  exclude: string[] = ["page", "pageBuilder"],
): Promise<string[]> {
  let entries: string[];
  try {
    entries = await readdir(schemasDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
  const excludeSet = new Set(["index", ...exclude]);
  return entries
    .filter((f) => f.endsWith(".ts"))
    .map((f) => f.slice(0, -3))
    .filter((n) => !excludeSet.has(n))
    .sort();
}

/**
 * Rewrite `{schemasDir}/index.ts` from scanned filenames, placing
 * `pageBuilder` and `page` last so `allSchemaTypes` is usable as a single
 * array plug-in to `defineConfig({ schema: { types } })`.
 */
export async function rewriteBarrelFromDisk(
  schemasDir: string,
  pageTypeName = "page",
  pageBuilderTypeName = "pageBuilder",
): Promise<string> {
  const components = await scanSchemaTypeNames(schemasDir, [
    pageTypeName,
    pageBuilderTypeName,
  ]);
  const allNames = [...components, pageBuilderTypeName, pageTypeName];
  const imports = allNames
    .map((n) => `import { ${n} } from "./${n}.ts";`)
    .join("\n");
  const src = `// GENERATED by aem-to-sanity-schema. Do not edit by hand.
${imports}

export const allSchemaTypes = [${allNames.join(", ")}];
${allNames.map((n) => `export { ${n} };`).join("\n")}
`;
  const file = join(schemasDir, "index.ts");
  await writeTextFile(file, src);
  return file;
}
