import { readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  writeJson,
  writeTextFile,
  type Logger,
  type PageComponentConfig,
} from "aem-to-sanity-core";
import {
  RESERVED_SANITY_TYPE_NAMES,
  toCamelCase,
  toTitleCase,
} from "./naming.ts";

const GENERATED_MARKER = "GENERATED by aem-to-sanity-schema template-pages";

export interface TemplatePageManifestEntry {
  /** AEM resource type of the page-shell component (no `/apps/` prefix). */
  pageComponentResourceType: string;
  /** Sanity object type emitted for the page-shell dialog. */
  pageComponentSanityType: string;
  /** Raw `cq:template` path as authored on `jcr:content`. */
  cqTemplate: string;
  /** Sanity document type name emitted for this (resource type, template) pair. */
  sanityType: string;
  /** Studio-facing title for the document type. */
  sanityTitle: string;
}

export interface TemplatePageManifest {
  __generated: string;
  entries: TemplatePageManifestEntry[];
}

export interface WriteTemplatePageArtifactsOptions {
  /** Directory where schema .ts files are written (same as pageBuilder). */
  schemasDir: string;
  /**
   * Output dir for the cache manifest (`{outputDir}/cache/page-templates.json`).
   * If omitted, the manifest is not written (used by tests that only care
   * about the rendered .ts files).
   */
  manifestOutputDir?: string;
  /** Operator-declared page-shell components → templates pairing. */
  pageComponentsConfig: PageComponentConfig;
  /** Reverse index: AEM resource type → resolved Sanity type name. */
  typeNameByResourceType: Map<string, string>;
  /** Page-builder array type name. Default: "pageBuilder". */
  pageBuilderTypeName?: string;
  logger?: Logger;
}

export interface WriteTemplatePageArtifactsResult {
  manifestFile?: string;
  manifest: TemplatePageManifest;
  /** Sanity type names of page-shell objects that should be excluded from pageBuilder.of[]. */
  excludeFromPageBuilder: string[];
  /** Files written for per-template document types. */
  documentFiles: string[];
}

/**
 * Convert an AEM `cq:template` path into a stable Sanity type name suffixed
 * with `Page`.
 *
 *   /conf/uxp/settings/wcm/templates/plan-details  → "planDetailsPage"
 *   /conf/.../templates/news-article               → "newsArticlePage"
 *   plan-details                                   → "planDetailsPage"
 *
 * Falls back to the last non-empty segment when no `templates/` marker is
 * found; collisions with built-in Sanity types get the `aem` prefix (same
 * rule `resolveSanityTypeNames` applies to components).
 */
export function templatePathToTypeName(templatePath: string): string {
  const segments = templatePath.split("/").filter(Boolean);
  const marker = segments.lastIndexOf("templates");
  const tail =
    marker >= 0 ? segments.slice(marker + 1) : segments.slice(-1);
  if (tail.length === 0) {
    throw new Error(`Cannot derive type name from cq:template: ${templatePath}`);
  }
  const camel = toCamelCase(tail.join("-"));
  if (!camel) {
    throw new Error(`Cannot derive type name from cq:template: ${templatePath}`);
  }
  return `${camel}Page`;
}

/**
 * Studio-friendly title from a template path. Mirrors the same word-split
 * rules used by `toTitleCase`, with a "Page" suffix so the type's purpose is
 * obvious in the Studio "+ Add" menus and structure list.
 */
export function templatePathToTitle(templatePath: string): string {
  const segments = templatePath.split("/").filter(Boolean);
  const marker = segments.lastIndexOf("templates");
  const tail =
    marker >= 0 ? segments.slice(marker + 1) : segments.slice(-1);
  const base = toTitleCase(tail.join(" "));
  return base ? `${base} Page` : "Page";
}

/**
 * For each (page-component resource type, cq:template) declared in the
 * tenant's `aem-page-components.json`, render one Sanity document type:
 *
 *   defineType({
 *     name: "<template>Page",
 *     type: "document",
 *     fields: [title, slug, tags, pageProperties, featuredImage, cqTemplate, pageBuilder],
 *   })
 *
 * The `pageProperties` field type points at the Sanity object emitted for
 * the page-shell component (resolved through `typeNameByResourceType`),
 * which is the same object the schema emitter produces for every other
 * dialog. Page-shell types are returned in `excludeFromPageBuilder` so the
 * caller can drop them from `pageBuilder.of[]` — they're not blocks.
 *
 * Files are GENERATED-marker guarded the same way `pagebuilder.ts`
 * preserves hand-edits.
 */
export async function writeTemplatePageArtifacts(
  opts: WriteTemplatePageArtifactsOptions,
): Promise<WriteTemplatePageArtifactsResult> {
  const {
    schemasDir,
    manifestOutputDir,
    pageComponentsConfig,
    typeNameByResourceType,
    pageBuilderTypeName = "pageBuilder",
    logger,
  } = opts;

  const manifest: TemplatePageManifest = {
    __generated: GENERATED_MARKER,
    entries: [],
  };
  const excludeFromPageBuilder = new Set<string>();
  const documentFiles: string[] = [];

  if (pageComponentsConfig.size === 0) {
    let manifestFile: string | undefined;
    if (manifestOutputDir) {
      manifestFile = join(manifestOutputDir, "cache", "page-templates.json");
      await writeJson(manifestFile, manifest);
    }
    return {
      manifestFile,
      manifest,
      excludeFromPageBuilder: [],
      documentFiles,
    };
  }

  // Resolve every (resourceType, template) pair to a Sanity document name.
  // First pass: gather candidates so we can apply the same collision rules
  // resolveSanityTypeNames uses for components — reserved-name prefix +
  // numeric suffix on duplicates. The page-component object names already
  // exist in `typeNameByResourceType` (taken set seed).
  const taken = new Set<string>(typeNameByResourceType.values());

  for (const [resourceType, entry] of pageComponentsConfig.entries()) {
    const pageComponentSanityType = typeNameByResourceType.get(resourceType);
    if (!pageComponentSanityType) {
      logger?.warn(
        `template-pages: skipping page-component "${resourceType}" — no Sanity type emitted (is it listed in aem-component-paths?).`,
      );
      continue;
    }
    excludeFromPageBuilder.add(pageComponentSanityType);

    for (const cqTemplate of entry.templates) {
      let name: string;
      try {
        name = templatePathToTypeName(cqTemplate);
      } catch (err) {
        logger?.warn(
          `template-pages: ${(err as Error).message} — skipping.`,
        );
        continue;
      }
      if (RESERVED_SANITY_TYPE_NAMES.has(name) || taken.has(name)) {
        name = "aem" + name.charAt(0).toUpperCase() + name.slice(1);
      }
      if (taken.has(name)) {
        const root = name;
        let suffix = 2;
        do {
          name = `${root}${suffix++}`;
        } while (taken.has(name));
      }
      taken.add(name);

      const title = templatePathToTitle(cqTemplate);
      const file = join(schemasDir, `${name}.ts`);
      const wrote = await maybeWriteTemplatePage({
        file,
        typeName: name,
        title,
        pageComponentSanityType,
        pageBuilderTypeName,
        logger,
      });
      if (wrote) documentFiles.push(file);

      manifest.entries.push({
        pageComponentResourceType: resourceType,
        pageComponentSanityType,
        cqTemplate,
        sanityType: name,
        sanityTitle: title,
      });
    }
  }

  manifest.entries.sort((a, b) =>
    a.sanityType < b.sanityType ? -1 : a.sanityType > b.sanityType ? 1 : 0,
  );

  let manifestFile: string | undefined;
  if (manifestOutputDir) {
    manifestFile = join(manifestOutputDir, "cache", "page-templates.json");
    await writeJson(manifestFile, manifest);
  }

  return {
    manifestFile,
    manifest,
    excludeFromPageBuilder: Array.from(excludeFromPageBuilder),
    documentFiles,
  };
}

interface MaybeWriteTemplatePageArgs {
  file: string;
  typeName: string;
  title: string;
  pageComponentSanityType: string;
  pageBuilderTypeName: string;
  logger?: Logger;
}

async function maybeWriteTemplatePage(
  args: MaybeWriteTemplatePageArgs,
): Promise<boolean> {
  const { file, logger } = args;
  let existing: string | undefined;
  try {
    existing = await readFile(file, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
  if (existing !== undefined && !existing.includes(GENERATED_MARKER)) {
    logger?.info(
      `template-pages: preserving hand-authored ${file} (no GENERATED marker found)`,
    );
    return false;
  }
  await writeTextFile(file, renderTemplatePage(args));
  return true;
}

function renderTemplatePage(args: MaybeWriteTemplatePageArgs): string {
  const { typeName, title, pageComponentSanityType, pageBuilderTypeName } = args;
  return `// ${GENERATED_MARKER}. Safe to delete or replace.
// To author a custom document type for this AEM template, remove this file
// (or the marker comment) — the migration will not overwrite it. Custom
// types can still reference the generated ${pageBuilderTypeName} array and
// the ${pageComponentSanityType} page-properties object.
import { defineField, defineType } from "sanity";

export const ${typeName} = defineType({
  name: ${JSON.stringify(typeName)},
  title: ${JSON.stringify(title)},
  type: "document",
  // Field-groups split the document form into tabs. \`content\` is the
  // default authoring surface (title, slug, body); \`pageProperties\` holds
  // the AEM page-shell dialog values lifted from \`jcr:content\` plus the
  // \`cq:template\` traceback. Keeps the editor uncluttered when the page
  // dialog has a long tail of technical settings (\`pwaOrientation\`,
  // \`disableCache\`, \`pinPage\`, …).
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "pageProperties", title: "Page properties" },
  ],
  preview: {
    select: {
      title: "title",
      slug: "slug.current",
    },
    prepare({ title, slug }) {
      return {
        title:
          typeof title === "string" && title.trim() ? title.trim() : "Untitled page",
        subtitle:
          typeof slug === "string" && slug.trim() ? "/" + slug.trim() : undefined,
      };
    },
  },
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    // Lifted from AEM \`jcr:content/cq:tags\` by \`aem-transform\` and resolved
    // through the categories manifest from \`aem-tags\`. Remove this field if
    // the migration source has no page-level tags.
    defineField({
      name: "tags",
      type: "array",
      group: "content",
      of: [{ type: "reference", to: [{ type: "category" }] }],
    }),
    // Lifted from AEM \`jcr:content/cq:featuredimage\` by \`aem-transform\` —
    // the DAM reference is rewritten to a Sanity asset by \`aem-assets\`.
    defineField({ name: "featuredImage", type: "image", group: "content" }),
    defineField({
      name: ${JSON.stringify(pageBuilderTypeName)},
      type: ${JSON.stringify(pageBuilderTypeName)},
      group: "content",
    }),
    // Page-properties dialog lifted from the page-shell component's
    // \`cq:dialog\` and applied to authored values on \`jcr:content\`.
    defineField({
      name: "pageProperties",
      title: "Page properties",
      type: ${JSON.stringify(pageComponentSanityType)},
      group: "pageProperties",
    }),
    // AEM \`cq:template\` path, retained for traceability and to let scripts
    // filter pages by template after migration. Hidden by default in the
    // Studio — remove the \`hidden\` flag if authors should see it.
    defineField({
      name: "cqTemplate",
      type: "string",
      group: "pageProperties",
      readOnly: true,
      hidden: true,
    }),
  ],
});
`;
}
